
name: ariza_takip
description: Big project
publish_to: "none"
environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.18.0
  dropdown_search: ^5.0.3
  flutter_barcode_scanner: ^2.0.0
  firebase_core: ^2.10.0
  cloud_firestore: ^4.8.0
flutter:
  uses-material-design: true
