
name: ariza_takip
description: Ariza Takip Uygulamasi
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  cloud_firestore: ^5.0.0
  firebase_core: ^3.0.0

flutter:
  uses-material-design: true
